# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto update

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '5 3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write  # 允许推送代码
      packages: read   # 允许读取包

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Auto Update
      run: |
        echo "auto update start" >> ranking.log
        sh auto_run.sh >> ranking.log
        echo "auto update end" >> ranking.log

    - name: Commit
      run: |
        git config --global user.email uxiaopeng@gmail.com
        git config --global user.name yuxiaopeng
        git add .
        git commit -m"action:`date`"
        git push

#     - name: Push changes
#       uses: ad-m/github-push-action@master
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
